original_string = """\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWWNKOkxxdooooooooodxxk0KNWWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWNKkdlc;,,,,,,,,,',,,,,,,,;:codkKNWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWXOdc;,,,'',,,,,,,,,,,,,,,,,,,,,,,,;cdOXWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWXOo:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:dONWMMMMMMMMMMMMMM
MMMMMMMMMMMMWKxc;,,,,,,,,,,,,,;:ccllooollcc:;,,,,,,,,,,,,,;lkXWMMMMMMMMMMMM
MMMMMMMMMMWXx:,,,,,,,,,,,;coxOKXNNNWWWWWNNXX0Oxoc;,,,,,,,,,,,cxXWMMMMMMMMMM
MMMMMMMMMWKdc:::::::::cok0NWMMMMMMMMMMMMMMMMMMMWN0xl:,,,,,,,,,,cONMMMMMMMMM
MMMMMMMMMWNXXXXXXXXXXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMWNKxc,,,,,,,,,;dKWMMMMMMM
MMMMMMWNKKKXXKKKKXXKKKKKKKKKKKXXXXXKXXXXXNWWMMMMMMMMMWXkc,,,,,,,,,l0WMMMMMM
MMMMMNOl::::::::::::::::::::::::::::::::ccodkKNWMMMMMMMWXx:,,,,,,,,cOWMMMMM
MMMMW0c,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'',,,,;cx0NMMMMMMMWOc,,,,,,,,c0WMMMM
MMMWKl,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;o0WMMMMMMWKl,,,,,,,,oXMMMM
MMMNd;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,',,,,,,,,,,,,',:xXWMMMMMW0c,,,,,,,;xWMMM
MMW0c,,,,,,,:oxkkkkkkkkkkkkkkkkkkkkkkkxxoc;,,,,,,,';dXWMMMMMWk:,,,,,,,lKWMM
MMWx;,,,,,,,dXWMMMMMMMMMMMMMMMMMMMMMMMMWWN0o;,,,,,,,;xNMMMMMMXo,,,,,,,;kWMM
MMNo,,,,,,,;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNk:,,,,,,,c0WMMMMMWk;,,,,,,,dNMM
MMXo,,,,,,,c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo,,,,,,,;kWMMMMMWO:,,,,,,,oXMM
MMXo,,,,,,,c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,,,,,,,;kWMMMMMW0:,,,,,,,oXMM
MMXo,,,,,,,:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c,,,,,,,:OWMMMMMWO:,,,,,,,oXMM
MMNd,,,,,,,;xNMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOl,,,,,,,,oXMMMMMMNd,,,,,,,;xNMM
MMWO:,,,,,,,lKWMMMMMMMMMMMMMMMMWXXXXXXXK0xl;,,,,,,',c0WMMMMMW0c,,,,,,':OWMM
MMMXo,,,,,,,;dNMMMMMMMMMMMMMMMMXxc:::::;;,,,,,,,,,,c0WMMMMMMXd,,,,,,,,oXMMM
MMMWO:,,,,,,,:kNMMMMMMMMMMMMMMMWXx;',,,,,,,,,,,,,:dKWMMMMMMNx;,,,,,,,cOWMMM
MMMMNx;,,,,,,,:xNWMMMMMMMMMMMMMMMNk:,',,,,,,,,,:dKWMMMMMMMXx;,,,,,,';kNMMMM
MMMMMXd;,,,,,,,;oKWMMMMMMMMMMMMMMMW0l;,,,,,,,,,lKWMMMMMMWKo;,,,,,,,;xNMMMMM
MMMMMMXd;,,,,,,,,ckXWMMMMMMMMMMMMMMWXOd;,,,,,,,,l0WMMMWXx:,,,,,,,,;xNMMMMMM
MMMMMMMNk:,,,,,,,,,ckKWMMMMMMMMMMMMMMWNk:,,,,,,,,ckNNKxc,,,,,,,,,:kNMMMMMMM
MMMMMMMMW0l,,,,,,,,,,:dOXWMMMMMMMMMMMMMWOc,,,,,,,,;oo:,,,,,,,,,;o0WMMMMMMMM
MMMMMMMMMWXkc,,,,,,,,,,,:oxOXNWWMMMMMMMMWKo;'',,,,,',,,,,,,,,,ckNWMMMMMMMMM
MMMMMMMMMMMWXxc,,,,,,,,,,,,,:codxkkkOOOXWWXx:,,,,,,,,,,,,,,;ckXWMMMMMMMMMMM
MMMMMMMMMMMMMWXko:,,',,,,,,,,,,,,,,,,,,cONWNOc,,,,,,,,,,,:oOXWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWNKkl:,,,,,,,,,,,,,,,,,,,:xXWW0l,'',,,,:okKWWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWNKOdl:;,,,,,,,,,,,,,,,;oKWWXd;;:ldOXWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWNX0kxolc::;;;;;,,,,,l0WWNK0XNWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXKK000Odc;,,:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xl;;dXWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xodKWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKKNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"""

a = original_string.replace(",", " ")
final_str = a.replace("'", " ")